    tablename     |          indexname          |                                                             indexdef                                                             
------------------+-----------------------------+----------------------------------------------------------------------------------------------------------------------------------
 app_texts        | app_texts_pkey              | CREATE UNIQUE INDEX app_texts_pkey ON public.app_texts USING btree (id)
 criteria         | criteria_pkey               | CREATE UNIQUE INDEX criteria_pkey ON public.criteria USING btree (id)
 departments      | departments_pkey            | CREATE UNIQUE INDEX departments_pkey ON public.departments USING btree (id)
 departments      | idx_departments_parent      | CREATE INDEX idx_departments_parent ON public.departments USING btree (parent_id)
 participants     | idx_participants_department | CREATE INDEX idx_participants_department ON public.participants USING btree (department_id)
 participants     | idx_participants_manager    | CREATE INDEX idx_participants_manager ON public.participants USING btree (is_manager)
 participants     | idx_participants_survey     | CREATE INDEX idx_participants_survey ON public.participants USING btree (survey_id)
 participants     | participants_pkey           | CREATE UNIQUE INDEX participants_pkey ON public.participants USING btree (id)
 partner_feedback | idx_feedback_partner        | CREATE INDEX idx_feedback_partner ON public.partner_feedback USING btree (partner_id)
 partner_feedback | partner_feedback_pkey       | CREATE UNIQUE INDEX partner_feedback_pkey ON public.partner_feedback USING btree (id)
 partner_feedback | unique_feedback             | CREATE UNIQUE INDEX unique_feedback ON public.partner_feedback USING btree (participant_id, partner_id)
 partners         | idx_partner_active          | CREATE INDEX idx_partner_active ON public.partners USING btree (active)
 partners         | partners_name_key           | CREATE UNIQUE INDEX partners_name_key ON public.partners USING btree (name)
 partners         | partners_pkey               | CREATE UNIQUE INDEX partners_pkey ON public.partners USING btree (id)
 ratings          | idx_ratings_criterion       | CREATE INDEX idx_ratings_criterion ON public.ratings USING btree (criterion_id)
 ratings          | idx_ratings_participant     | CREATE INDEX idx_ratings_participant ON public.ratings USING btree (participant_id)
 ratings          | idx_ratings_partner         | CREATE INDEX idx_ratings_partner ON public.ratings USING btree (partner_id)
 ratings          | idx_ratings_partner_type    | CREATE INDEX idx_ratings_partner_type ON public.ratings USING btree (partner_id, rating_type)
 ratings          | idx_ratings_type            | CREATE INDEX idx_ratings_type ON public.ratings USING btree (rating_type)
 ratings          | ratings_pkey                | CREATE UNIQUE INDEX ratings_pkey ON public.ratings USING btree (id)
 ratings          | unique_vote_per_survey      | CREATE UNIQUE INDEX unique_vote_per_survey ON public.ratings USING btree (participant_id, criterion_id, partner_id, rating_type)
 surveys          | idx_survey_active           | CREATE INDEX idx_survey_active ON public.surveys USING btree (is_active)
 surveys          | surveys_pkey                | CREATE UNIQUE INDEX surveys_pkey ON public.surveys USING btree (id)
(23 rows)

